% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Statistical Inference Course Project - Part 2},
  pdfauthor={Willem Hogewoning},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Statistical Inference Course Project - Part 2}
\author{Willem Hogewoning}
\date{8-2-2021}

\begin{document}
\maketitle

\hypertarget{statistical-inference-course-project}{%
\section{Statistical Inference Course
Project}\label{statistical-inference-course-project}}

\hypertarget{part-2-basic-inferential-data-analysis-instructions}{%
\subsection{Part 2: Basic Inferential Data Analysis
Instructions}\label{part-2-basic-inferential-data-analysis-instructions}}

Now in the second portion of the project, we're going to analyze the
ToothGrowth data in the R datasets package.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Load the ToothGrowth data and perform some basic exploratory data
  analyses
\item
  Provide a basic summary of the data.
\item
  Use confidence intervals and/or hypothesis tests to compare tooth
  growth by supp and dose. (Only use the techniques from class, even if
  there's other approaches worth considering)
\item
  State your conclusions and the assumptions needed for your
  conclusions.
\end{enumerate}

\textbf{First load the data and take a look}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(datasets)}
\KeywordTok{str}\NormalTok{(ToothGrowth)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    60 obs. of  3 variables:
##  $ len : num  4.2 11.5 7.3 5.8 6.4 10 11.2 11.2 5.2 7 ...
##  $ supp: Factor w/ 2 levels "OJ","VC": 2 2 2 2 2 2 2 2 2 2 ...
##  $ dose: num  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(ToothGrowth)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       len        supp         dose      
##  Min.   : 4.20   OJ:30   Min.   :0.500  
##  1st Qu.:13.07   VC:30   1st Qu.:0.500  
##  Median :19.25           Median :1.000  
##  Mean   :18.81           Mean   :1.167  
##  3rd Qu.:25.27           3rd Qu.:2.000  
##  Max.   :33.90           Max.   :2.000
\end{verbatim}

The data consists out of 60 observations, divided into two groups of 30.

Lets see the data in a visual

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\NormalTok{datamean <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{(len}\OperatorTok{~}\NormalTok{.,}\DataTypeTok{data=}\NormalTok{ToothGrowth,mean)}
\NormalTok{plot <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(ToothGrowth,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{dose,}\DataTypeTok{y=}\NormalTok{len))}
\NormalTok{plot <-}\StringTok{ }\NormalTok{plot }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{group=}\NormalTok{supp,}\DataTypeTok{colour=}\NormalTok{supp))}
\NormalTok{plot <-}\StringTok{ }\NormalTok{plot }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_line}\NormalTok{(}\DataTypeTok{data=}\NormalTok{datamean,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{group=}\NormalTok{supp,}\DataTypeTok{colour=}\NormalTok{supp))}
\NormalTok{plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project1-part2_files/figure-latex/two-1.pdf}

In the plot we can see that as the dosage increases, the average length
also increases. However for the dosis of 2.0 the average doesn't show a
difference anymore.

\hypertarget{comparison}{%
\subsection{Comparison}\label{comparison}}

Lets see the comparison between the 3 different dosses that are in the
data set

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data_OJ <-}\StringTok{ }\NormalTok{ToothGrowth[}\DecValTok{31}\OperatorTok{:}\DecValTok{60}\NormalTok{,]}
\NormalTok{data_VC <-}\StringTok{ }\NormalTok{ToothGrowth[}\DecValTok{1}\OperatorTok{:}\DecValTok{30}\NormalTok{,]}
\NormalTok{len_difference <-}\StringTok{ }\NormalTok{data_OJ}\OperatorTok{$}\NormalTok{len }\OperatorTok{-}\StringTok{ }\NormalTok{data_VC}\OperatorTok{$}\NormalTok{len}
\NormalTok{data <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(len_difference, data_OJ}\OperatorTok{$}\NormalTok{dose)}
\KeywordTok{names}\NormalTok{(data) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"len_difference"}\NormalTok{, }\StringTok{"dose"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\textbf{For the dosis of 0.5}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dose_}\FloatTok{0.5}\NormalTok{ <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(data, dose }\OperatorTok{==}\StringTok{ }\FloatTok{0.5}\NormalTok{)}
\KeywordTok{t.test}\NormalTok{(dose_}\FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  dose_0.5
## t = 2.8295, df = 19, p-value = 0.01071
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.7483243 5.0016757
## sample estimates:
## mean of x 
##     2.875
\end{verbatim}

Has a positive mean in the confidence interval, with a p-value of
0.01071, meaning both methods are different.

\textbf{For the dosis of 1.0}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dose_}\FloatTok{1.0}\NormalTok{ <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(data, dose }\OperatorTok{==}\StringTok{ }\FloatTok{1.0}\NormalTok{)}
\KeywordTok{t.test}\NormalTok{(dose_}\FloatTok{1.0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  dose_1.0
## t = 3.3779, df = 19, p-value = 0.003158
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  1.318017 5.611983
## sample estimates:
## mean of x 
##     3.465
\end{verbatim}

Has a positive mean in the confidence interval, with a p-value of
0.003158, meaning both methods are different.

\textbf{For the dosis of 2.0}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dose_}\FloatTok{1.0}\NormalTok{ <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(data, dose }\OperatorTok{==}\StringTok{ }\FloatTok{2.0}\NormalTok{)}
\KeywordTok{t.test}\NormalTok{(dose_}\FloatTok{1.0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  dose_1.0
## t = 1.0162, df = 19, p-value = 0.3223
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -1.01732  2.93732
## sample estimates:
## mean of x 
##      0.96
\end{verbatim}

Has a positive mean in the confidence interval, but with a p-value of
0.3223, meaning we cannot make any conclusions

\end{document}
