% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Project-part1},
  pdfauthor={Willem Hogewoning},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Project-part1}
\author{Willem Hogewoning}
\date{7-2-2021}

\begin{document}
\maketitle

\hypertarget{part-1-simulation-exercise-instructions}{%
\section{Part 1: Simulation Exercise
Instructions}\label{part-1-simulation-exercise-instructions}}

In this project you will investigate the exponential distribution in R
and compare it with the Central Limit Theorem. The exponential
distribution can be simulated in R with rexp(n, lambda) where lambda is
the rate parameter. The mean of exponential distribution is 1/lambda and
the standard deviation is also 1/lambda. Set lambda = 0.2 for all of the
simulations. You will investigate the distribution of averages of 40
exponentials. Note that you will need to do a thousand simulations.

Illustrate via simulation and associated explanatory text the properties
of the distribution of the mean of 40 exponentials. You should

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Show the sample mean and compare it to the theoretical mean of the
  distribution.
\item
  Show how variable the sample is (via variance) and compare it to the
  theoretical variance of the distribution.
\item
  Show that the distribution is approximately normal.
\end{enumerate}

\hypertarget{stimulation}{%
\subsection{Stimulation}\label{stimulation}}

Bot means for the sample and the one according the Central Limit Theorem
(CLT) are calculated below.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#parameters}
\NormalTok{lambda <-}\StringTok{ }\FloatTok{0.2}
\NormalTok{mean <-}\StringTok{ }\DecValTok{1}\OperatorTok{/}\NormalTok{lambda}
\NormalTok{sd <-}\StringTok{ }\DecValTok{1}\OperatorTok{/}\NormalTok{lambda}
\NormalTok{n <-}\StringTok{ }\DecValTok{40}
\NormalTok{simulations <-}\StringTok{ }\DecValTok{1000}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{12345}\NormalTok{)}

\CommentTok{#stimulation}
\NormalTok{datamatrix <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{rexp}\NormalTok{(simulations }\OperatorTok{*}\StringTok{ }\NormalTok{n, }\DataTypeTok{rate=}\NormalTok{lambda), simulations, n)}
\NormalTok{datamean <-}\StringTok{ }\KeywordTok{rowMeans}\NormalTok{(datamatrix)         }
\end{Highlighting}
\end{Shaded}

Show the plot of the stimulation

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(datamean)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project1-part1_files/figure-latex/two-1.pdf}

\hypertarget{show-the-sample-mean-and-compare-it-to-the-theoretical-mean-of-the-distribution.}{%
\subsection{1. Show the sample mean and compare it to the theoretical
mean of the
distribution.}\label{show-the-sample-mean-and-compare-it-to-the-theoretical-mean-of-the-distribution.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stimulationmean <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(datamean)}
\NormalTok{clt_mean <-}\StringTok{ }\DecValTok{1}\OperatorTok{/}\NormalTok{lambda}


\NormalTok{stimulationvariance <-}\StringTok{ }\KeywordTok{var}\NormalTok{(datamean)}
\NormalTok{clt_varieance <-}\StringTok{ }\NormalTok{(}\DecValTok{1}\OperatorTok{/}\NormalTok{lambda)}\OperatorTok{^}\DecValTok{2}\OperatorTok{/}\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\textbf{The mean}

The actual mean versus the CLT mean:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Mean}
\NormalTok{stimulationmean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.971972
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{clt_mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5
\end{verbatim}

The actual mean is 4.97 versus the CLT mean of 5.00; quite close to each
other

\hypertarget{show-how-variable-the-sample-is-via-variance-and-compare-it-to-the-theoretical-variance-of-the-distribution.}{%
\subsection{2. Show how variable the sample is (via variance) and
compare it to the theoretical variance of the
distribution.}\label{show-how-variable-the-sample-is-via-variance-and-compare-it-to-the-theoretical-variance-of-the-distribution.}}

\textbf{The variance}

The actual mean versus the CLT mean:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Variance}
\NormalTok{stimulationvariance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6157926
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{clt_varieance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.625
\end{verbatim}

The actual varience is 0.62 verus the CLT variance of 0.63; quite close
each other

\hypertarget{show-that-the-distribution-is-approximately-normal.}{%
\subsection{3. Show that the distribution is approximately
normal.}\label{show-that-the-distribution-is-approximately-normal.}}

First we show approximately by normal by looking at the shape:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}

\KeywordTok{library}\NormalTok{(ggplot2)}

\NormalTok{plotdata <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(datamean);}

\NormalTok{plot <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(plotdata, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{datamean))}
\NormalTok{plot <-}\StringTok{ }\NormalTok{plot }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_histogram}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y=}\NormalTok{..density..),}\DataTypeTok{bins=}\DecValTok{30}\NormalTok{)}
\NormalTok{plot }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{colour=}\StringTok{"blue"}\NormalTok{, }\DataTypeTok{size=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project1-part1_files/figure-latex/six-1.pdf} as one can
see the shape looks like a normal distribution

Second we look at the confidence intervals

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stimulation_confidence_interval  <-}\StringTok{ }\KeywordTok{round}\NormalTok{ (}\KeywordTok{mean}\NormalTok{(datamean) }\OperatorTok{+}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{)}\OperatorTok{*}\FloatTok{1.96}\OperatorTok{*}\KeywordTok{sd}\NormalTok{(datamean)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n),}\DecValTok{3}\NormalTok{)}
\NormalTok{clt_confidence_interval <-}\StringTok{ }\NormalTok{clt_mean }\OperatorTok{+}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{)}\OperatorTok{*}\FloatTok{1.96}\OperatorTok{*}\KeywordTok{sqrt}\NormalTok{(clt_varieance)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n)}

\NormalTok{stimulation_confidence_interval}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.729 5.215
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{clt_confidence_interval}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.755 5.245
\end{verbatim}

The actual 95\% confidence interval is {[}4.729 5.215{]} the CTL 95\%
confidence interval is {[}4.749 5.254{]} both quite close to each other

Third we look at the Q-Q plot

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qqnorm}\NormalTok{(datamean); }\KeywordTok{qqline}\NormalTok{(datamean)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project1-part1_files/figure-latex/eight-1.pdf}

Also here we can see it lies quite inline.

\end{document}
